# Generated by Django 3.2.9 on 2022-07-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_student_edt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(choices=[('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('passout', 'passout')], max_length=8),
        ),
    ]
